oysterprotocol/webinterface

html/file-encrypt-demo-2.html, javascripts/encryption.js, javascripts/file-processor.js
- Add encryption to file chunks
- Refactor to reuse file chunking method across both alpha and beta
=> Add encryption to file chunks and refactor

html/file-encrypt-demo-2.html, javascripts/file-processor.js
- Uses placeholder api hostname for now
=> Create upload session before sending chunks

oyster/package.json, oyster/yarn.lock
- Version conflict with jest dependency
=> Remove babel-jest

oyster/package.json, oyster/src/config/index.js, oyster/src/setup-tests.js, oyster/src/tests/utils/file-processor.test.js, oyster/src/utils/file-processor.js, oyster/yarn.lock
- Adds test for creating upload session
=> Add upload session test

oyster/package.json, oyster/src/redux/effects/broker-node-client.js, oyster/yarn.lock
Corresponding [broker node PR](https://github.com/oysterprotocol/brokernode/pull/20)
=> Adds function to poll broker node for chunk status

.babelrc, package.json, src/components/main/index.js, src/config/index.js, src/redux/actions/file-actions.js, src/redux/epics/file-epic.js, src/redux/reducers/file-reducer.js, src/services/iota.js, src/tests/utils/file-processor.test.js, src/utils/datamap.js, src/utils/file-processor.js, yarn.lock
- Install IOTA
- Creates datamap (unoptimized, optimization will come in next pull)
- Update chunk byte size from 30 to 1000
=> Installs IOTA

package.json, src/components/main/index.js, src/config/index.js, src/redux/actions/file-actions.js, src/redux/epics/file-epic.js, src/services/iota.js, src/tests/utils/file-processor.test.js, src/utils/datamap.js, src/utils/encryption.js, src/utils/file-processor.js, yarn.lock
- Updates path for uploading chunks + fixes params
- Match the encryption method with the backend
- Fix IOTA address creation
=> Fix QA bugs with uploading chunks

src/components/main/index.js, src/config/index.js, src/redux/actions/download-actions.js, src/redux/epics/download-epic.js, src/redux/index.js, src/services/iota.js, src/utils/file-processor.js
=> Retrieve file from user inputted handle

src/components/root.css, src/components/upload-complete/index.js, src/components/upload-started/index.js, src/redux/epics/download-epic.js, src/redux/index.js, src/utils/file-processor.js
- Converts messages to trytes before sending them to broker
=> Em debug upload

src/services/iota.js
=> Uniq transactions

src/services/iota.js
Adding uniq transactions to uploads too.
=> Adding uniq transactions to uploads too.

src/redux/epics/download-epic.js, src/services/backend.js, src/utils/file-processor.js
- Encrypt whole file before chunking. Before it was encrypting each chunk individually, which was causing the chunks sent to alpha and beta to differ
=> Fix issue with chunk pairs having different messages

src/config/index.js, src/redux/actions/upload-actions.js, src/redux/epics/download-epic.js, src/redux/epics/playground-epic.js, src/redux/epics/upload-epic.js, src/redux/reducers/upload-reducer.js, src/services/backend.js, src/utils/file-processor.js
- Simplify chunking by encoding, encrypting, and tryting the whole file at once
- Enable beta broker
- Fixes playground
- Maximizes tangle message character length
=> Tryte entire file at once

package.json, public/index.html, src/index.js, src/services/analytics.js, yarn.lock
- Currently only tracks home page visit
=> Installs Segment for event tracking

package.json, src/index.js, src/services/error-tracker.js, yarn.lock
Confirmed that it works with: https://sentry.io/oyster-pearl/webinterface/
=> Installs Sentry for error tracking

src/config/index.js, src/redux/epics/download-epic.js, src/redux/epics/upload-epic.js, src/services/iota.js
-Can only ask for 1000 chunks at a time.  This fixes large downloads which were breaking
-Did not realize that Jet's lightTransactionObject changes never actually get merged into the master branch.  So, I've included those changes as well.
=> Large downloads

src/redux/epics/download-epic.js, src/redux/epics/upload-epic.js, src/utils/encryption.js, src/utils/encryption.test.js
-small fixes to get Jet's changes to work
-updates unit tests for encryption.js
Don't merge until datamap-generator package updated!  Merge corresponding brokernode review at the same time.
=> Change handle conversion

src/config/index.js, src/redux/epics/upload-epic.js
Not a real fix, but could help ease the load on out tangle.
=> Quick fix. Reduce load to IOTA by half.

src/components/upload-started/upload-started-slide.js
This reverts commit c7d696bf48e695038fd1c7670db76a63fe9ba613.
=> Revert "min progress"

src/components/root.css, src/components/upload-form/upload-slide.js, src/redux/reducers/upload-reducer.js
- Added disabled color and cursor classes
- Set the ethAddress to be initialized to an empty string
=> Limited uploads to 1 year

src/config/index.js
=> use real addresses

src/utils/encryption.js, src/utils/file-processor.js
Still need to discuss how to handle illegal characters. I personally favor replacing whitespace with "_" and stripping the rest but the downside is that this is added complexity which may not be expected.
=> [Webinterface] Only allow certain characters in the handle 

.travis.yml, cypress.json, package.json
https://dashboard.cypress.io/#/projects/rpup8w/runs/8/specs
=> Integrated cypress tests with Travis CI

.travis.yml, README.md, cypress.json, cypress/integration/file-upload.js, package.json
- changed port to 3001 to avoid conflicts on brokernode
=> Added base url to get better error reporting

src/config/index.tsx
=> Last minute

src/config/index.tsx, src/services/oyster-stream.tsx
webinterface changes to utilize Jet's and Connor's streamable multi-provider changes
When deploying this make sure oyster-streamable is the latest version
=> Multiprovider compliance

package.json, src/components/download-form/download-form-slide.tsx, src/components/root.css, src/config/index.tsx, yarn.lock
- Just do it for download form slide
=> Start styled components migration

config/env.js, config/jest/cssTransform.js, config/jest/fileTransform.js, config/paths.js, config/polyfills.js, config/webpack.config.js, cypress/integration/file-upload.js, src/components/brokers-down/brokers-down-slide.tsx, src/components/brokers-down/index.tsx, src/components/download-form/index.tsx, src/components/error-page/index.tsx, src/components/payment-confirm/index.tsx, src/components/payment-invoice/payment-invoice-slide.tsx, src/components/shared/header.tsx, src/components/shared/icon_folder.tsx, src/components/shared/icon_sidebar.tsx, src/components/shared/slide-error.tsx, src/components/shared/slide.tsx, src/components/upload-complete/index.tsx, src/components/upload-form/index.tsx, src/components/upload-progress/index.tsx, src/services/oyster-stream.tsx
Committing these prettier formatting changes in a separate PR so they don't get mixed in with real changes.
=> Prettier formatting

cypress/integration/file-upload.js, package.json, package.json.orig, src/components/shared/progress-bar.jsx, src/components/upload-progress/index.tsx, src/components/upload-progress/upload-progress-slide.tsx, src/components/upload-progress/upload-started-slide.tsx, src/components/upload-started/index.tsx, src/components/upload-started/upload-started-slide.tsx, src/index.js, src/redux/actions/upload-actions.tsx, src/redux/epics/navigation-epic.tsx, src/redux/epics/upload-epic.tsx, src/redux/reducers/upload-reducer.tsx, src/services/oyster-stream.tsx, yarn.lock, yarn.lock.orig
Depends on https://github.com/oysterprotocol/oyster-streamable/pull/37
=> Continue upload ui

src/components/download-started/download-started-slide.tsx, src/components/error-page/error-page-slide.tsx, src/components/root.css, yarn.lock
- Migrate a few components to styled-components
=> Refactor styles

package.json, src/components/upload-progress/upload-progress-slide.tsx, src/components/upload-started/upload-started-slide.tsx, src/redux/actions/upload-actions.tsx, src/redux/epics/upload-epic.tsx, src/redux/reducers/upload-history-reducer.test.js, src/redux/reducers/upload-reducer.test.js, src/redux/reducers/upload-reducer.tsx, src/services/oyster-stream.tsx, yarn.lock
Depends on https://github.com/oysterprotocol/webinterface/pull/263
=> Better polling qa

src/config/index.tsx, src/services/oyster-stream.tsx
It's okay to go ahead and merge this, but let's not deploy until we have the new polling node up.
=> tangle update
